### ISSUE TITLE
[Feature Request] Patch regexp_instr for Trino, so that its compatible in dbt-expectations

### ISSUE THREAD

**Issue by aezomz** [starburstdata/dbt-trino-utils#21]
Patch regexp_instr for Trino, so that its compatible in dbt-expectations

Reference, of why am here.
https://github.com/calogica/dbt-expectations/issues/243

Is your feature request related to a problem? Please describe.
Lets support regex expectation for Trino on
https://github.com/calogica/dbt-expectations/blob/b21b13f020f5df2c90885d0715a2e713d1204700/macros/regex/regexp_instr.sql

Describe the solution you'd like
We can use this,
https://trino.io/docs/current/functions/regexp.html
regexp_position(string, pattern, start, occurrence) → integer

Lets group similar implementation like https://github.com/dbt-msft/tsql-utils/tree/main/macros/dbt_expectations ?

**Comment by wjhrdy** [comment]
instead of waiting on this to get worked on I just made a quick fork of the fork and I'm overriding the function ontop of this repo

packages.yml

```
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: calogica/dbt_expectations
    version: 0.10.0
  - package: starburstdata/trino_utils
    version: 0.6.0
  - git: https://github.com/wjhrdy/dbt-trino-utils.git
    revision: 0.2.0
```

dbt_project.yml
```
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['trino_utils', 'dbt_utils']
  - macro_namespace: dbt_date
    search_order: ['trino_utils', 'dbt_date']
  - macro_namespace: metrics
    search_order: ['trino_utils', 'metrics']
  - macro_namespace: dbt_expectations
    search_order: ['trino_utils_expectations', 'dbt_expectations']
```

this makes expectations work
